openapi: 3.1.0
info:
  x-logo:
    url: https://docs.incomingemailapi.com/logo.png
  title: "Incoming email API"
  version: "1.0.0"
  contact:
    name: Support
    email: support@waldeck.io
    url: https://www.incomingemailapi.com
servers:
  - url: https://api.incomingemailapi.com/v1
security:
  - ApiKey: []
tags:
  - name: Inbox
  - name: Custom domains
webhooks:
  newEmail:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sender:
                  type: string
                  format: email
                subject:
                  type: string
                text:
                  type: string
                html:
                  type: string
                attachments:
                  type: array
                  items:
                    type: string
                    format: uri
                raw:
                  type: string
paths:
  /domains:
    post:
      tags: [Custom domains]
      summary: Create domain
      responses:
        '201': 
          description: Domain is created but not validated yet. Will only be valid if MX records match with your DNS setup.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/singleDomainResponse' 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createDomain' 
    get:
      tags: [Custom domains]
      summary: Retreive domains
      responses:
        '200': 
          description: All domains, active and inactive, you've created
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/singleDomainResponse'
  /domains/{id}:
    
    get:
      tags: [Custom domains]
      summary: Retreive single domain
      responses:
        '200': 
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/singleDomainResponse'
    delete:
      tags: [Custom domains]
      summary: Remove domain
      responses:
        '204': 
          $ref: './components.yaml#/components/responses/204'
        '404':
          $ref: './components.yaml#/components/responses/404'
  /inbox:
    post:
      tags: [Inbox]
      summary: Create new inbox
      responses:
        '201':
          description: Created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/singleInboxResponse'
        '400':
          $ref: './components.yaml#/components/responses/400'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createInbox'
  /inbox{id}:
    get:
      tags: [Inbox]
      summary: Retreive single inbox
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/singleInboxResponse'
        '404':
          $ref: './components.yaml#/components/responses/404'
    delete:
      tags: [Inbox]
      summary: Remove inbox
      responses:
        '204':
          $ref: './components.yaml#/components/responses/204'
        '404':
          $ref: './components.yaml#/components/responses/404'
components:
  schemas:
    createInbox:
      type: object
      properties:
        localPart:
          type: string
          description: The local-part of the inbox, the part before the `@domain` of the e-mailaddress. If not provided, we will generate it instead.
          example: account-639
        domain:
          type: string
          description: The domain of the inbox, the part after the `local-part@` of the e-mailaddress. Needs to match with one of your validated domains.
          example: finance.acme.com
        callbackUrl:
          type: string
          format: uri
          description: URL invoked when a new email has been sent to this inbox. Overrides domain's `callbackURL`.
          example: https://api.acme.com/handle-new-email
    singleInboxResponse:
      allOf:
        - type: object
          properties:
            id:
              type: string
              format: uuid
        - $ref: '#/components/schemas/createInbox'
    singleDomainResponse:
      allOf:
        - type: object
          properties:
            id:
              type: string
              format: uuid
            valid:
              type: boolean
              example: false
            mxRecords:
              type: array
              example: ['23.123.123.43', '36.631.34.45']
              items:
                type: string
        - $ref: '#/components/schemas/createDomain'
    createDomain:
      type: object
      properties:
        domain:
          type: string
          description: The domain of the inbox, the part after the `local-part@` of the e-mailaddress.
          example: finance.acme.com
        callbackUrl:
          type: string
          format: uri
          description: URL invoked when a new email has been sent to this domain.
          example: https://api.acme.com/handle-new-email
          
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key