openapi: 3.1.0
info:
  x-logo:
    url: https://framerusercontent.com/images/yQVsnN5mU6YyAcTFn6CofIO8Fsw.png
    backgroundColor: "#0d111d"
  title: "Incoming email API"
  version: "1.0.0"
  contact:
    name: Support
    email: support@waldeck.io
    url: https://www.incomingemailapi.com
servers:
  - url: https://api.incomingemailapi.com/v1
tags:
  - name: Inbox
  - name: Custom domains
webhooks:
  newEmail:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sender:
                  type: string
                  format: email
                subject:
                  type: string
                text:
                  type: string
                html:
                  type: string
                attachments:
                  type: array
                  items:
                    type: string
                    format: uri
                raw:
                  type: string
paths:
  /domains:
    post:
      tags: [Custom domains]
      summary: Create domain
      responses:
        '201': 
          description: Domain is created but not validated yet. Will only be valid if MX records match with your DNS setup.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/singleDomainResponse' 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                domain:
                  type: string
                  description: The domain of the inbox, the part after the `local-part@` of the e-mailaddress.
                  example: example.com
                callbackUrl:
                  type: string
                  format: uri
                  description: URL invoked when a new email has been sent to this domain.
    get:
      tags: [Custom domains]
      summary: Retreive domains
      responses:
        '200': 
          description: All domains, active and inactive, you've created
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/singleDomainResponse' 
  /inbox:
    post:
      tags: [Inbox]
      summary: Create new inbox
      responses:
        '201':
          description: Created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/singleInboxResponse'
        '400':
          $ref: './components.yaml#/components/responses/400'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                localPart:
                  type: string
                  description: The local-part of the inbox, the part before the `@domain` of the e-mailaddress. If not provided, we will generate it instead.
                domain:
                  type: string
                  description: The domain of the inbox, the part after the `local-part@` of the e-mailaddress. Needs to match with one of your validated domains.
                  example: example.com
                callbackUrl:
                  type: string
                  format: uri
                  description: URL invoked when a new email has been sent to this inbox. Overrides domain's `callbackURL`.
components:
  schemas:
    singleInboxResponse:
      type: object
      properties:
        localPart:
          type: string
          example: user
        domain:
          type: string
          example: example.com
        callbackUrl:
          type: string
          format: uri
          description: URL invoked when a new email has been sent to this inbox. Overrides domain's `callbackURL`.
    singleDomainResponse:
      type: object
      properties:
        domain:
          type: string
          example: example.com
        valid:
          type: boolean
          example: false
        mxRecords:
          type: array
          example: ['23.123.123.43', '36.631.34.45']
          items:
            type: string
        callbackUrl:
          type: string
          format: uri
          description: URL invoked when a new email has been sent to this domain.