openapi: 3.1.0
info:
  x-logo:
    url: https://docs.mockingapi.com/logo.png
  title: "Mocking API"
  version: "1.0.0"
  contact:
    name: Support
    email: support@waldeck.io
    url: https://www.mockingapi.com
servers:
  - url: https://api.mockingapi.com/v1
security:
  - ApiKey: []
paths:
  /data:
    get:
      summary: Get data
      responses:
        '200': 
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/singleMessageResponse'
components:
  schemas:
    singleMessageResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key