openapi: 3.1.0
info:
  x-logo:
    url: https://docs.schedulingapi.io/logo.png
  title: "Scheduling API"
  description: |
    To make a request to the API you need to add the provided API key via the `X-Api-Key` request header. Using CURL, the command looks like:
    
    ```bash
    curl -X GET -H "X-Api-Key: API_KEY" ENDPOINT
    ```

    Replace **API_KEY** with your actual API key and **ENDPOINT** with the URL of the API endpoint you want to access.

    For example, if your API key is `0BE9F8UpT73VZFZYvtPSH5h5TolA9nTL6HgaPQC3`, the CURL command to get all tasks should look like this:
    ```bash
    curl -X GET -H "X-Api-Key: 0BE9F8UpT73VZFZYvtPSH5h5TolA9nTL6HgaPQC3" https://api.schedulingapi.io/v1/tasks
    ```
  version: "1.0.0"
  contact:
    name: Support
    email: support@schedulingapi.io
    url: https://www.schedulingapi.io
servers:
  - url: https://api.schedulingapi.io/v1
security:
  - ApiKey: []
paths:
  /tasks:
    post:
      summary: Create new task
      responses:
        '400':
          $ref: './components.yaml#/components/responses/400'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/singleTaskResponse'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createTask'
    get:
      summary: Retreive tasks
      responses:
        '200': 
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/singleTaskResponse'
  /tasks/{id}:
    get:
      summary: Retreive a single task
      responses:
        '200': 
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/singleTaskResponse' 
        '404':
          $ref: './components.yaml#/components/responses/404'
    delete:
      summary: Remove task
      responses:
        '204': 
          $ref: './components.yaml#/components/responses/204'
        '404':
          $ref: './components.yaml#/components/responses/404'

components:
  schemas:
    createTask:
      type: object
      properties:
        name:
          type: string
        executeAt:
          type: string
          format: date-time
        request:
          $ref: '#/components/schemas/request'
        recurringSchedule:
          $ref: '#/components/schemas/schedule'
    singleTaskResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        nextExecution:
          type: string
          format: date-time
        lastExecution:
          type: string
          format: date-time
        request:
          $ref: '#/components/schemas/request'
        recurringSchedule:
          $ref: '#/components/schemas/schedule'
    schedule:
      type: object
      properties:
        expiresAt:
          type: string
          format: date-time
        hours:
          type: array
          items:
            type: integer
            minimum: 0
            maximum: 23
        minutes:
          type: array
          items:
            type: integer
            minimum: 1
            maximum: 60
        months:
          type: array
          items:
            type: integer
            minimum: 1
            maximum: 12
        daysOfWeek:
          type: array
          items:
            type: integer
            minimum: 1
            maximum: 7
        daysOfMonth:
          type: array
          items:
            type: integer
            minimum: 1
            maximum: 31
    request:
      type: object
      properties:
        url:
          type: string
          format: uri
        method:
          type: string
          enum: [GET, POST, OPTIONS, HEAD, PUT, DELETE, TRACE, CONNECT, PATCH]
        body:
          type: string
        headers:
          type: object
          example: {'key': 'value'}

  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key