openapi: 3.1.0
info:
  x-logo:
    url: https://docs.webhooksapi.io/logo.png
  title: "Webhooks API"
  description: |
    To make a request to the API you need to add the provided API key via the `X-Api-Key` request header. Using CURL, the command looks like:
    
    ```bash
    curl -X GET -H "X-Api-Key: API_KEY" ENDPOINT
    ```

    Replace **API_KEY** with your actual API key and **ENDPOINT** with the URL of the API endpoint you want to access.

    For example, if your API key is `0BE9F8UpT73VZFZYvtPSH5h5TolA9nTL6HgaPQC3`, the CURL command to get all messages should look like this:
    ```bash
    curl -X GET -H "X-Api-Key: 0BE9F8UpT73VZFZYvtPSH5h5TolA9nTL6HgaPQC3" https://api.webhooksapi.io/v1/messages
    ```
  version: "1.0.0"
  contact:
    name: Support
    email: support@webhooksapi.io
    url: https://www.webhooksapi.io
servers:
  - url: https://api.webhooksapi.io/v1
security:
  - ApiKey: []
paths:
  /messages:
    post:
      tags: [Messages]
      summary: Create new message
      responses:
        '400':
          $ref: './components.yaml#/components/responses/400'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/singleMessageResponse'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createMessage'
    get:
      tags: [Messages]
      summary: Retreive messages
      responses:
        '200': 
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/singleMessageResponse'
  /messages/{id}:
    get:
      tags: [Messages]
      summary: Retreive single message
      responses:
        '200': 
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/singleMessageResponse'
        '404':
          $ref: './components.yaml#/components/responses/404'
  /applications:
    get:
      tags: [Applications]
      summary: Retreive applications
      responses:
        '200': 
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/singleApplicationResponse'
    post:
      tags: [Applications]
      summary: Create new application
      responses:
        '400':
          $ref: './components.yaml#/components/responses/400'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/singleApplicationResponse'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createApplication'
  /applications/{id}:
    get:
      tags: [Applications]
      summary: Retreive single application
      responses:
        '200': 
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/singleApplicationResponse'
        '404':
          $ref: './components.yaml#/components/responses/404'
    delete:
      tags: [Applications]
      summary: Remove application
      responses:
        allOf:
        - $ref: './components.yaml#/components/responses/204'
        - $ref: './components.yaml#/components/responses/404'
components:
  schemas:
    createMessage:
      type: object
      properties:
        eventType:
          type: string
        applicationId:
          type: uuid
        payload:
          type: object
          example: {'key': 'value'}
    singleMessageResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        eventType:
          type: string
        applicationId:
          type: uuid
        payload:
          type: object
        createdAt:
          type: date-time
    createApplication:
      type: object
      properties:
        name:
          type: string
        uid:
          type: string
    singleApplicationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        uid:
          type: string

  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key